# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2022-03-21T18:18:50+00:00

from __future__ import annotations

from typing import List
from uuid import UUID

from fastapi import FastAPI

from .models import ReadingCreateRequest, ReadingResponse, ReadingUpdateRequest

app = FastAPI(
    description='A service for managing the blood glucose readings of diabetes patients',
    title='Blood Glucose Readings API',
    version='1.0.0',
)


@app.get('/v1/reading', response_model=List[ReadingResponse])
def get_v1_reading() -> List[ReadingResponse]:
    """
    Get all readings
    """
    pass


@app.post('/v1/reading', response_model=None)
def post_v1_reading(body: ReadingCreateRequest) -> None:
    """
    Create a new reading
    """
    pass


@app.get('/v1/reading/{reading_uuid}', response_model=ReadingResponse)
def get_v1_reading_reading_uuid(reading_uuid: UUID) -> ReadingResponse:
    """
    Get a reading by UUID
    """
    pass


@app.put('/v1/reading/{reading_uuid}', response_model=None)
def put_v1_reading_reading_uuid(
    reading_uuid: UUID, body: ReadingUpdateRequest = ...
) -> None:
    """
    Update a reading by UUID
    """
    pass


@app.delete('/v1/reading/{reading_uuid}', response_model=None)
def delete_v1_reading_reading_uuid(reading_uuid: UUID) -> None:
    """
    Delete a reading by UUID
    """
    pass
