# generated by fastapi-codegen:
#   filename:  backend-technical-test-master/openapi.yaml
#   timestamp: 2022-03-21T18:18:50+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional
from uuid import UUID

from pydantic import BaseModel, Field


class Unit(Enum):
    mmol_L = 'mmol/L'
    mg_dL = 'mg/dL'


class ReadingCreateRequest(BaseModel):
    patient_uuid: UUID = Field(
        ...,
        description='The UUID of the patient who took the reading',
        example='22c685ae-9249-4c84-9b6e-d0e3537be66e',
    )
    value: float = Field(
        ..., description='The value of the blood glucose reading', example=5.5
    )
    unit: Unit = Field(
        ...,
        description='The unit that the blood glucose reading is recorded in (either mmol/L or mg/dL)',
    )
    recorded_at: datetime = Field(
        ...,
        description='The timestamp at which the reading was recorded, in ISO8601 format '
                    '(see https://en.wikipedia.org/wiki/ISO_8601)',
        example='2021-01-01T12:00:00+00:00',
    )


class ReadingResponse(BaseModel):
    reading_uuid: UUID = Field(
        ...,
        description='The UUID of the reading',
        example='1faafa60-c19a-4dd1-b5b0-e1d55f9464d4',
    )
    patient_uuid: UUID = Field(
        ...,
        description='The UUID of the patient who took the reading',
        example='22c685ae-9249-4c84-9b6e-d0e3537be66e',
    )
    value: float = Field(
        ..., description='The value of the blood glucose reading', example=5.5
    )
    unit: Unit = Field(
        ...,
        description='The unit that the blood glucose reading is recorded in (either mmol/L or mg/dL)',
    )
    recorded_at: datetime = Field(
        ...,
        description='The timestamp at which the reading was recorded, in ISO8601 format '
                    '(see https://en.wikipedia.org/wiki/ISO_8601)',
        example='2021-01-01T12:00:00+00:00',
    )

    class Config:
        orm_mode = True


class ReadingUpdateRequest(BaseModel):
    patient_uuid: Optional[UUID] = Field(
        None,
        description='The UUID of the patient who took the reading',
        example='22c685ae-9249-4c84-9b6e-d0e3537be66e',
    )
    value: Optional[float] = Field(
        None, description='The value of the blood glucose reading', example=5.5
    )
    unit: Optional[Unit] = Field(
        None,
        description='The unit that the blood glucose reading is recorded in (either mmol/L or mg/dL)',
    )
    recorded_at: Optional[datetime] = Field(
        None,
        description='The timestamp at which the reading was recorded, in ISO8601 format '
                    '(see https://en.wikipedia.org/wiki/ISO_8601)',
        example='2021-01-01T12:00:00+00:00',
    )
